const billTypes = [
  "CONSULTATION",
  "LABORATORY",
  "PRESCRIPTIONS",
  "PROCEDURES",
  "CONSUMABLES",
  "MISCELLANEOUS",
];

const MISCELLANEOUS_TYPES = [
  "ACCOMMODATION",
  "NURSING_CARE",
  "MEDICAL_REVIEWS",
  "EXAMINATION",
  "OUT_OF_POCKET",
  "STAMP_DUTY",
  "MISCELLANEOUS",
];

module.exports = { billTypes, MISCELLANEOUS_TYPES };
